In [31]:
import pandas as pd
import numpy as np
import random

In [35]:
sample = {'AUTO':[0, 0, 1, 1, 0], 'BUS':[0, 1, 0, 1, 0], 'BIKE':[0, 0, 1, 1, 0], 'WFH':[0,0,1,0,0]}
df = pd.DataFrame(data=sample)
df['Rand Assignment'] = ""
df

   AUTO  BUS  BIKE  WFH Rand Assignment
0     0    0     0    0
1     0    1     0    0
2     1    0     1    1
3     1    1     1    0
4     0    0     0    0

In [38]:
modes = ['AUTO', 'BUS', 'BIKE', 'WFH']

for index, rows in df.iterrows():
    available_indices = []
    if df['AUTO'][index] == 1:
        available_indices.append(0)
    if df['BUS'][index] == 1:
        available_indices.append(1)
    if df['BIKE'][index] == 1:
        available_indices.append(2)
    if df['WFH'][index] == 1:
        available_indices.append(3)
    if len(available_indices) == 0:
        df['Rand Assignment'][index] = "No option"
    else:
        RandAssignment = random.choice(available_indices)
        df['Rand Assignment'][index] = modes[RandAssignment]
    
df

C:\Users\amber.jiang\Anaconda3\envs\geopandas_env\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\amber.jiang\Anaconda3\envs\geopandas_env\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

   AUTO  BUS  BIKE  WFH Rand Assignment
0     0    0     0    0       No option
1     0    1     0    0             BUS
2     1    0     1    1            BIKE
3     1    1     1    0             BUS
4     0    0     0    0       No option